spring:
  cloud:
    gateway:
      routes:
      - id: session
        uri: http://localhost/
        predicates:
        - Path=/session
        filters:
        - RewritePath=/session/(?<segment>.*),/session/$\{segment}
      - id: httpbin
        uri: http://httpbin.org
        predicates:
          - Path=/get
