spring:
  cloud:
    gateway:
      routes:
      - id: session
        uri: http://localhost/
        predicates:
        - Path=/session
      - id: httpbin
        uri: http://httpbin.org
        predicates:
          - Path=/get
